from setuptools import setup

setup(
    name='flask',
    version='',
    packages=['venv', 'venv.lib', 'venv.lib.python3.7', 'venv.lib.python3.7.site-packages',
              'venv.lib.python3.7.site-packages.bs4', 'venv.lib.python3.7.site-packages.bs4.tests',
              'venv.lib.python3.7.site-packages.bs4.builder', 'venv.lib.python3.7.site-packages.boto',
              'venv.lib.python3.7.site-packages.boto.gs', 'venv.lib.python3.7.site-packages.boto.s3',
              'venv.lib.python3.7.site-packages.boto.ec2', 'venv.lib.python3.7.site-packages.boto.ec2.elb',
              'venv.lib.python3.7.site-packages.boto.ec2.autoscale',
              'venv.lib.python3.7.site-packages.boto.ec2.cloudwatch', 'venv.lib.python3.7.site-packages.boto.ecs',
              'venv.lib.python3.7.site-packages.boto.emr', 'venv.lib.python3.7.site-packages.boto.fps',
              'venv.lib.python3.7.site-packages.boto.iam', 'venv.lib.python3.7.site-packages.boto.kms',
              'venv.lib.python3.7.site-packages.boto.mws', 'venv.lib.python3.7.site-packages.boto.rds',
              'venv.lib.python3.7.site-packages.boto.sdb', 'venv.lib.python3.7.site-packages.boto.sdb.db',
              'venv.lib.python3.7.site-packages.boto.sdb.db.manager', 'venv.lib.python3.7.site-packages.boto.ses',
              'venv.lib.python3.7.site-packages.boto.sns', 'venv.lib.python3.7.site-packages.boto.sqs',
              'venv.lib.python3.7.site-packages.boto.sts', 'venv.lib.python3.7.site-packages.boto.swf',
              'venv.lib.python3.7.site-packages.boto.vpc', 'venv.lib.python3.7.site-packages.boto.file',
              'venv.lib.python3.7.site-packages.boto.logs', 'venv.lib.python3.7.site-packages.boto.rds2',
              'venv.lib.python3.7.site-packages.boto.mturk', 'venv.lib.python3.7.site-packages.boto.pyami',
              'venv.lib.python3.7.site-packages.boto.pyami.installers',
              'venv.lib.python3.7.site-packages.boto.pyami.installers.ubuntu',
              'venv.lib.python3.7.site-packages.boto.manage', 'venv.lib.python3.7.site-packages.boto.roboto',
              'venv.lib.python3.7.site-packages.boto.cacerts', 'venv.lib.python3.7.site-packages.boto.cognito',
              'venv.lib.python3.7.site-packages.boto.cognito.sync',
              'venv.lib.python3.7.site-packages.boto.cognito.identity', 'venv.lib.python3.7.site-packages.boto.contrib',
              'venv.lib.python3.7.site-packages.boto.glacier', 'venv.lib.python3.7.site-packages.boto.kinesis',
              'venv.lib.python3.7.site-packages.boto.mashups', 'venv.lib.python3.7.site-packages.boto.route53',
              'venv.lib.python3.7.site-packages.boto.route53.domains', 'venv.lib.python3.7.site-packages.boto.support',
              'venv.lib.python3.7.site-packages.boto.cloudhsm', 'venv.lib.python3.7.site-packages.boto.dynamodb',
              'venv.lib.python3.7.site-packages.boto.opsworks', 'venv.lib.python3.7.site-packages.boto.redshift',
              'venv.lib.python3.7.site-packages.boto.services', 'venv.lib.python3.7.site-packages.boto.vendored',
              'venv.lib.python3.7.site-packages.boto.vendored.regions',
              'venv.lib.python3.7.site-packages.boto.awslambda', 'venv.lib.python3.7.site-packages.boto.beanstalk',
              'venv.lib.python3.7.site-packages.boto.dynamodb2', 'venv.lib.python3.7.site-packages.boto.cloudfront',
              'venv.lib.python3.7.site-packages.boto.cloudtrail', 'venv.lib.python3.7.site-packages.boto.codedeploy',
              'venv.lib.python3.7.site-packages.boto.cloudsearch', 'venv.lib.python3.7.site-packages.boto.elasticache',
              'venv.lib.python3.7.site-packages.boto.cloudsearch2',
              'venv.lib.python3.7.site-packages.boto.datapipeline',
              'venv.lib.python3.7.site-packages.boto.configservice',
              'venv.lib.python3.7.site-packages.boto.directconnect',
              'venv.lib.python3.7.site-packages.boto.cloudformation',
              'venv.lib.python3.7.site-packages.boto.machinelearning',
              'venv.lib.python3.7.site-packages.boto.cloudsearchdomain',
              'venv.lib.python3.7.site-packages.boto.elastictranscoder',
              'venv.lib.python3.7.site-packages.boto.ec2containerservice', 'venv.lib.python3.7.site-packages.bson',
              'venv.lib.python3.7.site-packages.idna', 'venv.lib.python3.7.site-packages.lxml',
              'venv.lib.python3.7.site-packages.lxml.html', 'venv.lib.python3.7.site-packages.lxml.includes',
              'venv.lib.python3.7.site-packages.lxml.isoschematron', 'venv.lib.python3.7.site-packages.pytz',
              'venv.lib.python3.7.site-packages.boto3', 'venv.lib.python3.7.site-packages.boto3.s3',
              'venv.lib.python3.7.site-packages.boto3.ec2', 'venv.lib.python3.7.site-packages.boto3.docs',
              'venv.lib.python3.7.site-packages.boto3.dynamodb', 'venv.lib.python3.7.site-packages.boto3.resources',
              'venv.lib.python3.7.site-packages.click', 'venv.lib.python3.7.site-packages.flask',
              'venv.lib.python3.7.site-packages.flask.json', 'venv.lib.python3.7.site-packages.numpy',
              'venv.lib.python3.7.site-packages.numpy.ma', 'venv.lib.python3.7.site-packages.numpy.ma.tests',
              'venv.lib.python3.7.site-packages.numpy.doc', 'venv.lib.python3.7.site-packages.numpy.fft',
              'venv.lib.python3.7.site-packages.numpy.fft.tests', 'venv.lib.python3.7.site-packages.numpy.lib',
              'venv.lib.python3.7.site-packages.numpy.lib.tests', 'venv.lib.python3.7.site-packages.numpy.core',
              'venv.lib.python3.7.site-packages.numpy.core.tests', 'venv.lib.python3.7.site-packages.numpy.f2py',
              'venv.lib.python3.7.site-packages.numpy.f2py.tests', 'venv.lib.python3.7.site-packages.numpy.tests',
              'venv.lib.python3.7.site-packages.numpy.compat', 'venv.lib.python3.7.site-packages.numpy.compat.tests',
              'venv.lib.python3.7.site-packages.numpy.linalg', 'venv.lib.python3.7.site-packages.numpy.linalg.tests',
              'venv.lib.python3.7.site-packages.numpy.random', 'venv.lib.python3.7.site-packages.numpy.random.tests',
              'venv.lib.python3.7.site-packages.numpy.random.tests.data',
              'venv.lib.python3.7.site-packages.numpy.testing', 'venv.lib.python3.7.site-packages.numpy.testing.tests',
              'venv.lib.python3.7.site-packages.numpy.testing._private',
              'venv.lib.python3.7.site-packages.numpy.distutils',
              'venv.lib.python3.7.site-packages.numpy.distutils.tests',
              'venv.lib.python3.7.site-packages.numpy.distutils.command',
              'venv.lib.python3.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.7.site-packages.numpy.matrixlib',
              'venv.lib.python3.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.7.site-packages.numpy.polynomial',
              'venv.lib.python3.7.site-packages.numpy.polynomial.tests', 'venv.lib.python3.7.site-packages.scipy',
              'venv.lib.python3.7.site-packages.scipy.io', 'venv.lib.python3.7.site-packages.scipy.io.arff',
              'venv.lib.python3.7.site-packages.scipy.io.arff.tests', 'venv.lib.python3.7.site-packages.scipy.io.tests',
              'venv.lib.python3.7.site-packages.scipy.io.matlab',
              'venv.lib.python3.7.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.7.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.7.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.7.site-packages.scipy.fft', 'venv.lib.python3.7.site-packages.scipy.fft._pocketfft',
              'venv.lib.python3.7.site-packages.scipy.fft._pocketfft.tests',
              'venv.lib.python3.7.site-packages.scipy.odr', 'venv.lib.python3.7.site-packages.scipy.odr.tests',
              'venv.lib.python3.7.site-packages.scipy._lib', 'venv.lib.python3.7.site-packages.scipy._lib.tests',
              'venv.lib.python3.7.site-packages.scipy._lib._uarray', 'venv.lib.python3.7.site-packages.scipy.misc',
              'venv.lib.python3.7.site-packages.scipy.misc.tests', 'venv.lib.python3.7.site-packages.scipy.stats',
              'venv.lib.python3.7.site-packages.scipy.stats.tests', 'venv.lib.python3.7.site-packages.scipy.linalg',
              'venv.lib.python3.7.site-packages.scipy.linalg.tests', 'venv.lib.python3.7.site-packages.scipy.signal',
              'venv.lib.python3.7.site-packages.scipy.signal.tests',
              'venv.lib.python3.7.site-packages.scipy.signal.windows', 'venv.lib.python3.7.site-packages.scipy.sparse',
              'venv.lib.python3.7.site-packages.scipy.sparse.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.7.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.7.site-packages.scipy.cluster', 'venv.lib.python3.7.site-packages.scipy.cluster.tests',
              'venv.lib.python3.7.site-packages.scipy.fftpack', 'venv.lib.python3.7.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.7.site-packages.scipy.ndimage', 'venv.lib.python3.7.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.7.site-packages.scipy.spatial', 'venv.lib.python3.7.site-packages.scipy.spatial.tests',
              'venv.lib.python3.7.site-packages.scipy.spatial.transform',
              'venv.lib.python3.7.site-packages.scipy.spatial.transform.tests',
              'venv.lib.python3.7.site-packages.scipy.special', 'venv.lib.python3.7.site-packages.scipy.special.tests',
              'venv.lib.python3.7.site-packages.scipy.special._precompute',
              'venv.lib.python3.7.site-packages.scipy.optimize', 'venv.lib.python3.7.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.7.site-packages.scipy.optimize.tests',
              'venv.lib.python3.7.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.7.site-packages.scipy.optimize._shgo_lib',
              'venv.lib.python3.7.site-packages.scipy.optimize.cython_optimize',
              'venv.lib.python3.7.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib.python3.7.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib.python3.7.site-packages.scipy.constants',
              'venv.lib.python3.7.site-packages.scipy.constants.tests',
              'venv.lib.python3.7.site-packages.scipy.integrate',
              'venv.lib.python3.7.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.7.site-packages.scipy.integrate.tests',
              'venv.lib.python3.7.site-packages.scipy.interpolate',
              'venv.lib.python3.7.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.7.site-packages.scipy._build_utils',
              'venv.lib.python3.7.site-packages.scipy._build_utils.tests', 'venv.lib.python3.7.site-packages.gensim',
              'venv.lib.python3.7.site-packages.gensim.viz', 'venv.lib.python3.7.site-packages.gensim.test',
              'venv.lib.python3.7.site-packages.gensim.models',
              'venv.lib.python3.7.site-packages.gensim.models.wrappers',
              'venv.lib.python3.7.site-packages.gensim.models.deprecated',
              'venv.lib.python3.7.site-packages.gensim.corpora', 'venv.lib.python3.7.site-packages.gensim.parsing',
              'venv.lib.python3.7.site-packages.gensim.scripts', 'venv.lib.python3.7.site-packages.gensim.sklearn_api',
              'venv.lib.python3.7.site-packages.gensim.similarities',
              'venv.lib.python3.7.site-packages.gensim.summarization',
              'venv.lib.python3.7.site-packages.gensim.topic_coherence', 'venv.lib.python3.7.site-packages.gridfs',
              'venv.lib.python3.7.site-packages.jinja2', 'venv.lib.python3.7.site-packages.joblib',
              'venv.lib.python3.7.site-packages.joblib.test', 'venv.lib.python3.7.site-packages.joblib.test.data',
              'venv.lib.python3.7.site-packages.joblib.externals',
              'venv.lib.python3.7.site-packages.joblib.externals.loky',
              'venv.lib.python3.7.site-packages.joblib.externals.loky.backend',
              'venv.lib.python3.7.site-packages.joblib.externals.cloudpickle',
              'venv.lib.python3.7.site-packages.pandas', 'venv.lib.python3.7.site-packages.pandas.io',
              'venv.lib.python3.7.site-packages.pandas.io.sas', 'venv.lib.python3.7.site-packages.pandas.io.json',
              'venv.lib.python3.7.site-packages.pandas.io.excel', 'venv.lib.python3.7.site-packages.pandas.io.formats',
              'venv.lib.python3.7.site-packages.pandas.io.clipboard', 'venv.lib.python3.7.site-packages.pandas.api',
              'venv.lib.python3.7.site-packages.pandas.api.types',
              'venv.lib.python3.7.site-packages.pandas.api.indexers',
              'venv.lib.python3.7.site-packages.pandas.api.extensions', 'venv.lib.python3.7.site-packages.pandas.core',
              'venv.lib.python3.7.site-packages.pandas.core.ops', 'venv.lib.python3.7.site-packages.pandas.core.util',
              'venv.lib.python3.7.site-packages.pandas.core.tools',
              'venv.lib.python3.7.site-packages.pandas.core.arrays',
              'venv.lib.python3.7.site-packages.pandas.core.arrays.sparse',
              'venv.lib.python3.7.site-packages.pandas.core.dtypes',
              'venv.lib.python3.7.site-packages.pandas.core.sparse',
              'venv.lib.python3.7.site-packages.pandas.core.window',
              'venv.lib.python3.7.site-packages.pandas.core.groupby',
              'venv.lib.python3.7.site-packages.pandas.core.indexes',
              'venv.lib.python3.7.site-packages.pandas.core.reshape',
              'venv.lib.python3.7.site-packages.pandas.core.internals',
              'venv.lib.python3.7.site-packages.pandas.core.computation',
              'venv.lib.python3.7.site-packages.pandas.util', 'venv.lib.python3.7.site-packages.pandas._libs',
              'venv.lib.python3.7.site-packages.pandas._libs.tslibs',
              'venv.lib.python3.7.site-packages.pandas._libs.window', 'venv.lib.python3.7.site-packages.pandas.tests',
              'venv.lib.python3.7.site-packages.pandas.tests.io',
              'venv.lib.python3.7.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.7.site-packages.pandas.tests.io.json',
              'venv.lib.python3.7.site-packages.pandas.tests.io.excel',
              'venv.lib.python3.7.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.7.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.7.site-packages.pandas.tests.io.pytables',
              'venv.lib.python3.7.site-packages.pandas.tests.api', 'venv.lib.python3.7.site-packages.pandas.tests.base',
              'venv.lib.python3.7.site-packages.pandas.tests.util',
              'venv.lib.python3.7.site-packages.pandas.tests.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.frame.methods',
              'venv.lib.python3.7.site-packages.pandas.tests.tools',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.sparse',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.string_',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.categorical',
              'venv.lib.python3.7.site-packages.pandas.tests.config',
              'venv.lib.python3.7.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.7.site-packages.pandas.tests.dtypes.cast',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.7.site-packages.pandas.tests.series',
              'venv.lib.python3.7.site-packages.pandas.tests.series.methods',
              'venv.lib.python3.7.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.7.site-packages.pandas.tests.window',
              'venv.lib.python3.7.site-packages.pandas.tests.generic',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.multi',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.ranges',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.categorical',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries.holiday',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries.frequencies',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing.multiindex',
              'venv.lib.python3.7.site-packages.pandas.tests.plotting',
              'venv.lib.python3.7.site-packages.pandas.tests.resample',
              'venv.lib.python3.7.site-packages.pandas.tests.extension',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.list',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.arrow',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.7.site-packages.pandas.tests.internals',
              'venv.lib.python3.7.site-packages.pandas.tests.arithmetic',
              'venv.lib.python3.7.site-packages.pandas.tests.reductions',
              'venv.lib.python3.7.site-packages.pandas.tests.computation',
              'venv.lib.python3.7.site-packages.pandas.arrays', 'venv.lib.python3.7.site-packages.pandas.compat',
              'venv.lib.python3.7.site-packages.pandas.compat.numpy', 'venv.lib.python3.7.site-packages.pandas.errors',
              'venv.lib.python3.7.site-packages.pandas._config', 'venv.lib.python3.7.site-packages.pandas.tseries',
              'venv.lib.python3.7.site-packages.pandas.plotting',
              'venv.lib.python3.7.site-packages.pandas.plotting._matplotlib', 'venv.lib.python3.7.site-packages.psutil',
              'venv.lib.python3.7.site-packages.psutil.tests', 'venv.lib.python3.7.site-packages.soynlp',
              'venv.lib.python3.7.site-packages.soynlp.ner', 'venv.lib.python3.7.site-packages.soynlp.pos',
              'venv.lib.python3.7.site-packages.soynlp.noun', 'venv.lib.python3.7.site-packages.soynlp.word',
              'venv.lib.python3.7.site-packages.soynlp.utils', 'venv.lib.python3.7.site-packages.soynlp.hangle',
              'venv.lib.python3.7.site-packages.soynlp.postagger',
              'venv.lib.python3.7.site-packages.soynlp.postagger.tagset',
              'venv.lib.python3.7.site-packages.soynlp.tokenizer', 'venv.lib.python3.7.site-packages.soynlp.lemmatizer',
              'venv.lib.python3.7.site-packages.soynlp.normalizer',
              'venv.lib.python3.7.site-packages.soynlp.predicator',
              'venv.lib.python3.7.site-packages.soynlp.vectorizer', 'venv.lib.python3.7.site-packages.tweepy',
              'venv.lib.python3.7.site-packages.certifi', 'venv.lib.python3.7.site-packages.chardet',
              'venv.lib.python3.7.site-packages.chardet.cli', 'venv.lib.python3.7.site-packages.pymongo',
              'venv.lib.python3.7.site-packages.sklearn', 'venv.lib.python3.7.site-packages.sklearn.svm',
              'venv.lib.python3.7.site-packages.sklearn.svm.tests', 'venv.lib.python3.7.site-packages.sklearn.tree',
              'venv.lib.python3.7.site-packages.sklearn.tree.tests', 'venv.lib.python3.7.site-packages.sklearn.tests',
              'venv.lib.python3.7.site-packages.sklearn.utils', 'venv.lib.python3.7.site-packages.sklearn.utils.tests',
              'venv.lib.python3.7.site-packages.sklearn.impute',
              'venv.lib.python3.7.site-packages.sklearn.impute.tests',
              'venv.lib.python3.7.site-packages.sklearn.cluster',
              'venv.lib.python3.7.site-packages.sklearn.cluster.tests',
              'venv.lib.python3.7.site-packages.sklearn.compose',
              'venv.lib.python3.7.site-packages.sklearn.compose.tests',
              'venv.lib.python3.7.site-packages.sklearn.metrics',
              'venv.lib.python3.7.site-packages.sklearn.metrics._plot',
              'venv.lib.python3.7.site-packages.sklearn.metrics._plot.tests',
              'venv.lib.python3.7.site-packages.sklearn.metrics.tests',
              'venv.lib.python3.7.site-packages.sklearn.metrics.cluster',
              'venv.lib.python3.7.site-packages.sklearn.metrics.cluster.tests',
              'venv.lib.python3.7.site-packages.sklearn.mixture',
              'venv.lib.python3.7.site-packages.sklearn.mixture.tests',
              'venv.lib.python3.7.site-packages.sklearn.datasets',
              'venv.lib.python3.7.site-packages.sklearn.datasets.tests',
              'venv.lib.python3.7.site-packages.sklearn.ensemble',
              'venv.lib.python3.7.site-packages.sklearn.ensemble.tests',
              'venv.lib.python3.7.site-packages.sklearn.ensemble._hist_gradient_boosting',
              'venv.lib.python3.7.site-packages.sklearn.ensemble._hist_gradient_boosting.tests',
              'venv.lib.python3.7.site-packages.sklearn.manifold',
              'venv.lib.python3.7.site-packages.sklearn.manifold.tests',
              'venv.lib.python3.7.site-packages.sklearn.externals',
              'venv.lib.python3.7.site-packages.sklearn.externals.joblib',
              'venv.lib.python3.7.site-packages.sklearn.neighbors',
              'venv.lib.python3.7.site-packages.sklearn.neighbors.tests',
              'venv.lib.python3.7.site-packages.sklearn.covariance',
              'venv.lib.python3.7.site-packages.sklearn.covariance.tests',
              'venv.lib.python3.7.site-packages.sklearn.inspection',
              'venv.lib.python3.7.site-packages.sklearn.inspection.tests',
              'venv.lib.python3.7.site-packages.sklearn._build_utils',
              'venv.lib.python3.7.site-packages.sklearn.experimental',
              'venv.lib.python3.7.site-packages.sklearn.experimental.tests',
              'venv.lib.python3.7.site-packages.sklearn.linear_model',
              'venv.lib.python3.7.site-packages.sklearn.linear_model.tests',
              'venv.lib.python3.7.site-packages.sklearn.__check_build',
              'venv.lib.python3.7.site-packages.sklearn.decomposition',
              'venv.lib.python3.7.site-packages.sklearn.decomposition.tests',
              'venv.lib.python3.7.site-packages.sklearn.preprocessing',
              'venv.lib.python3.7.site-packages.sklearn.preprocessing.tests',
              'venv.lib.python3.7.site-packages.sklearn.neural_network',
              'venv.lib.python3.7.site-packages.sklearn.neural_network.tests',
              'venv.lib.python3.7.site-packages.sklearn.model_selection',
              'venv.lib.python3.7.site-packages.sklearn.model_selection.tests',
              'venv.lib.python3.7.site-packages.sklearn.semi_supervised',
              'venv.lib.python3.7.site-packages.sklearn.semi_supervised.tests',
              'venv.lib.python3.7.site-packages.sklearn.gaussian_process',
              'venv.lib.python3.7.site-packages.sklearn.gaussian_process.tests',
              'venv.lib.python3.7.site-packages.sklearn.feature_selection',
              'venv.lib.python3.7.site-packages.sklearn.feature_selection.tests',
              'venv.lib.python3.7.site-packages.sklearn.feature_extraction',
              'venv.lib.python3.7.site-packages.sklearn.feature_extraction.tests',
              'venv.lib.python3.7.site-packages.sklearn.cross_decomposition',
              'venv.lib.python3.7.site-packages.sklearn.cross_decomposition.tests',
              'venv.lib.python3.7.site-packages.urllib3', 'venv.lib.python3.7.site-packages.urllib3.util',
              'venv.lib.python3.7.site-packages.urllib3.contrib',
              'venv.lib.python3.7.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.urllib3.packages',
              'venv.lib.python3.7.site-packages.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.botocore', 'venv.lib.python3.7.site-packages.botocore.docs',
              'venv.lib.python3.7.site-packages.botocore.docs.bcdoc',
              'venv.lib.python3.7.site-packages.botocore.retries', 'venv.lib.python3.7.site-packages.botocore.vendored',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages.urllib3',
              'venv.lib.python3.7.site-packages.colorama', 'venv.lib.python3.7.site-packages.dateutil',
              'venv.lib.python3.7.site-packages.dateutil.tz', 'venv.lib.python3.7.site-packages.dateutil.parser',
              'venv.lib.python3.7.site-packages.dateutil.zoneinfo', 'venv.lib.python3.7.site-packages.docutils',
              'venv.lib.python3.7.site-packages.docutils.utils', 'venv.lib.python3.7.site-packages.docutils.utils.math',
              'venv.lib.python3.7.site-packages.docutils.parsers',
              'venv.lib.python3.7.site-packages.docutils.parsers.rst',
              'venv.lib.python3.7.site-packages.docutils.parsers.rst.languages',
              'venv.lib.python3.7.site-packages.docutils.parsers.rst.directives',
              'venv.lib.python3.7.site-packages.docutils.readers', 'venv.lib.python3.7.site-packages.docutils.writers',
              'venv.lib.python3.7.site-packages.docutils.writers.xetex',
              'venv.lib.python3.7.site-packages.docutils.writers.latex2e',
              'venv.lib.python3.7.site-packages.docutils.writers.odf_odt',
              'venv.lib.python3.7.site-packages.docutils.writers.s5_html',
              'venv.lib.python3.7.site-packages.docutils.writers.pep_html',
              'venv.lib.python3.7.site-packages.docutils.writers.html4css1',
              'venv.lib.python3.7.site-packages.docutils.writers.html5_polyglot',
              'venv.lib.python3.7.site-packages.docutils.languages',
              'venv.lib.python3.7.site-packages.docutils.transforms', 'venv.lib.python3.7.site-packages.jmespath',
              'venv.lib.python3.7.site-packages.oauthlib', 'venv.lib.python3.7.site-packages.oauthlib.oauth1',
              'venv.lib.python3.7.site-packages.oauthlib.oauth1.rfc5849',
              'venv.lib.python3.7.site-packages.oauthlib.oauth1.rfc5849.endpoints',
              'venv.lib.python3.7.site-packages.oauthlib.oauth2',
              'venv.lib.python3.7.site-packages.oauthlib.oauth2.rfc6749',
              'venv.lib.python3.7.site-packages.oauthlib.oauth2.rfc6749.clients',
              'venv.lib.python3.7.site-packages.oauthlib.oauth2.rfc6749.endpoints',
              'venv.lib.python3.7.site-packages.oauthlib.oauth2.rfc6749.grant_types',
              'venv.lib.python3.7.site-packages.oauthlib.openid',
              'venv.lib.python3.7.site-packages.oauthlib.openid.connect',
              'venv.lib.python3.7.site-packages.oauthlib.openid.connect.core',
              'venv.lib.python3.7.site-packages.oauthlib.openid.connect.core.endpoints',
              'venv.lib.python3.7.site-packages.oauthlib.openid.connect.core.grant_types',
              'venv.lib.python3.7.site-packages.requests', 'venv.lib.python3.7.site-packages.werkzeug',
              'venv.lib.python3.7.site-packages.werkzeug.debug', 'venv.lib.python3.7.site-packages.werkzeug.wrappers',
              'venv.lib.python3.7.site-packages.werkzeug.middleware', 'venv.lib.python3.7.site-packages.markupsafe',
              'venv.lib.python3.7.site-packages.s3transfer', 'venv.lib.python3.7.site-packages.smart_open',
              'venv.lib.python3.7.site-packages.smart_open.tests', 'venv.lib.python3.7.site-packages.itsdangerous',
              'venv.lib.python3.7.site-packages.requests_oauthlib',
              'venv.lib.python3.7.site-packages.requests_oauthlib.compliance_fixes'],
    url='',
    license='',
    author='seyoung',
    author_email='',
    description=''
)
